### ISSUE TITLE
Chore(deployment-service): rebase main branch

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-platform#203]
**Description**
The branch `feat/deployment-service` is out-of-date from the `main` branch, following are three main differences:
1. lint and type check
2. download zkeys and extract vkeys during `prepare` while calling `pnpm install`
3. remove vercel storage parts (only blob remains)
4. remove distribution parts
5. integrate with `subgraph`

**Possible Solution**
Tried rebasing before but there are too many conflicts, thinking about discarding current `feat/deployment-service` and open a new branch base on `main`. Luckily the deployment-service only affect few files.

**Comment by kittybest** [comment]
maybe could close this due to we might abandon the `feat/deployment-service` branch.

**Comment by kittybest** [comment]
hold because we might change to using coordinator service.

**Comment by ctrlc03** [comment]
Let's close this as the flow changed to do everything on the backend. The frontend will only have a dashboard for generating the deploymnet config
