### ISSUE TITLE
doc: update document on the setup part

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-platform#241]
**Description**
We now have default contracts, which allow the user not necessary to redeploy everything from scratch. Should include this description inside the `01_setup.md` file.

**Comment by ctrlc03** [comment]
I think we can directly link to https://maci.pse.dev/docs/quick-start/deployment

**Comment by kittybest** [comment]
> I think we can directly link to https://maci.pse.dev/docs/quick-start/deployment

Since there are still some instructions about maci-platform itself. So maybe just the part of setting up maci link to the url you provide?

**Comment by ctrlc03** [comment]
> Since there are still some instructions about maci-platform itself. So maybe just the part of setting up maci link to the url you provide?

yes, was referring to the maci deployment part only
