### ISSUE TITLE
Chore(interface): Graph is a little big, you can’t see the full data

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-platform#287]
**Description**
see picture here: https://www.notion.so/pse-team/MACI-Platform-and-MACI-v2-Testing-f8b9dbabc3454a398da74173c9299913

**Comment by aguzmant103** [comment]
Is this a bug? @kittybest

**Comment by ctrlc03** [comment]
Seems like this can be closed as we don't have a graph anymore for results but a leaderboard @kittybest @aguzmant103 ?

**Comment by aguzmant103** [comment]
Agreed, closing. @kittybest reopen it if you think otherwise
