### ISSUE TITLE
Feedback, votes are confusing

### ISSUE THREAD

**Issue by themighty1** [privacy-scaling-explorations/maci-platform#319]
Hi, I was casting a vote on https://www.voteathon.dev/ballot
I was shown that I have 1000 votes, so I expected to spread out those 1000 among the projects in the ballot. I couldn't do so, so I assumed the website was broken or not compatible with Firefox.
I was expecting to see some explanatory note about what exactly is the unit that Im supposed to enter for each project. That unit cannot be called a "vote" since apparently one unit is equivalent to ~20-30 votes.

**Comment by ctrlc03** [comment]
> Hi, I was casting a vote on https://www.voteathon.dev/ballot I was shown that I have 1000 votes, so I expected to spread out those 1000 among the projects in the ballot. I couldn't do so, so I assumed the website was broken or not compatible with Firefox. I was expecting to see some explanatory note about what exactly is the unit that Im supposed to enter for each project. That unit cannot be called a "vote" since apparently one unit is equivalent to ~20-30 votes.

@themighty1  thanks for the feedback. So that particular round you voted for uses quadratic voting, so each vote would spent vote * vote credits (i.e. vote 5 takes 25 credits) - agree we should make that clearer in the app. Where would you have liked to have that information?

**Comment by themighty1** [comment]
Thanks for explaining, I expected that info to be next to the field where you enter the votes. A small "?" with a mouse over popup would be good.

**Comment by ctrlc03** [comment]
> Thanks for explaining, I expected that info to be next to the field where you enter the votes. A small "?" with a mouse over popup would be good.

nice thanks!
