### ISSUE TITLE
UX: small change color of font during total votes during submit ballot page

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/maci-platform#384]
List of small UI changes needed:

- [x] "Total Votes" color in dark mode
- [x] Contribution Link should be required

1. The number next to "Total Votes" is not visible in dark mode![image](https://github.com/user-attachments/assets/b45c8395-07eb-4e22-90f9-574359ee8d6a)
![image](https://github.com/user-attachments/assets/0974b159-e8fe-4f0f-9173-b856b1952d6d)

2. Contribution Link should be marked required as it's preventing moving to next

![Image](https://github.com/user-attachments/assets/bc49ccdb-db92-4850-af74-cbfd905b98dd)

**Comment by crisgarner** [comment]
2. Should be fixed now, it was an old error
