### ISSUE TITLE
If an address has ENS display ENS

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-platform#393]

**Comment by varun-doshi** [comment]
I can take this up

**Comment by aguzmant103** [comment]
@varun-doshi go for it!

**Comment by aguzmant103** [comment]
@varun-doshi please week us updated at least once a week so we know it's been worked on :)

**Comment by varun-doshi** [comment]
> @varun-doshi please week us updated at least once a week so we know it's been worked on :)

Let me know if this looks good 
https://github.com/privacy-scaling-explorations/maci-platform/pull/506

**Comment by aguzmant103** [comment]
Issue merged, closing this one. Thanks for your contribution :) @varun-doshi
