### ISSUE TITLE
Improve upload metadata script

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-platform#423]
The script for uploading metadata requests the date as:

`When would you like to end the registration for applications? (Please respond in the format {Year}/{Month}/{Day} {Hour}:{Minute}:{Second} in UTC time)` 

If a user inputs `2024/10/25 17:30:00`, it should use UTC format, but the frontend instead takes the current time period turning the input as `Fri Oct 25 2024 17:30:00 UTC-6`

- A proposed solution would be to use, instead of requesting dates, only requests the duration of the period and use the poll deployment time + duration as a base. 

- Also we should only request the application period time and take the state based on the poll duration.

**Comment by ctrlc03** [comment]
> The script for uploading metadata requests the date as:
> 
> `When would you like to end the registration for applications? (Please respond in the format {Year}/{Month}/{Day} {Hour}:{Minute}:{Second} in UTC time)`
> 
> If a user inputs `2024/10/25 17:30:00`, it should use UTC format, but the frontend instead takes the current time period turning the input as `Fri Oct 25 2024 17:30:00 UTC-6`
> 
> * A proposed solution would be to use, instead of requesting dates, only requests the duration of the period and use the poll deployment time + duration as a base.
> * Also we should only request the application period time and take the state based on the poll duration.

Is this something that we think we should be maintaining? I would suggest for the time being we just have a json template and ask people to fill it up. Then all of this will be done via the frontend anyways

**Comment by kittybest** [comment]
> Is this something that we think we should be maintaining? I would suggest for the time being we just have a json template and ask people to fill it up. Then all of this will be done via the frontend anyways

I think we could have a json template for people to fill it up, and after the deployer dashboard deployed, just use the frontend.
Could open a PR to allow template and upload json file.
