### ISSUE TITLE
On review page, categories are not the same

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-platform#507]
![Screenshot 2024-11-29 at 4 11 12 PM](https://github.com/user-attachments/assets/574a992c-6ade-4980-a859-425310ab50bf)
![Screenshot 2024-11-29 at 4 11 07 PM](https://github.com/user-attachments/assets/ffc37a1c-6046-4962-9579-ce4691ceeca8)

**Comment by kittybest** [comment]
they are actually the same, but having different wording, I agree we should make them consistent.

**Comment by kittybest** [comment]
close by #518
